Fix json file generation
[GF-2856] nyx-utils generated json files have empty values

Change-Id: I8248db6d4b081786032562e780a1a3ce850c3a52
Reviewed-on: https://gpro.palm.com/1875
Reviewed-by: Pekka Ropo <pekka.ropo@palm.com>
Tested-by: Pekka Ropo <pekka.ropo@palm.com>
Reviewed-by: Keith Derrick <keith.derrick@lge.com>

diff --git a/files/launch/nyx-utils.in b/files/launch/nyx-utils.in
--- a/files/launch/nyx-utils.in
+++ b/files/launch/nyx-utils.in
@@ -39,6 +39,8 @@ script
     {
         echo "{" > $2
 
+        # enable non-zero exit codes for nyx-cmd
+        set +e
         for i in `print_query_list $1`; do
             val=`nyx-cmd $1 query $i`
             if [ $? = 0 ]; then
@@ -46,6 +48,8 @@ script
             fi
         done
 
+        #disable non-zero exit codes
+        set -e
         # remote last comma to make valid json
         sed -i '$ s/,$//' $2
 
